<a href="https://colab.research.google.com/github/Mell03y/Mell03y/blob/main/VB_YZ_Ders_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
import pandas as pd

**Series **

In [52]:
notlar = {"Gürhan": 50, "Ayşe": 60, "Leyla":70}

In [53]:
notlar

{'Gürhan': 50, 'Ayşe': 60, 'Leyla': 70}

In [54]:
pd.Series(notlar)

Gürhan    50
Ayşe      60
Leyla     70
dtype: int64

In [55]:
numpy_array = np.array([50,60,70,80])

In [56]:
numpy_array

array([50, 60, 70, 80])

In [57]:
pd.Series(numpy_array)

0    50
1    60
2    70
3    80
dtype: int64

**Data Frame**

In [58]:
data = np.random.randint(10, size=(4,4))

In [59]:
data

array([[9, 5, 5, 4],
       [7, 7, 4, 1],
       [4, 9, 2, 3],
       [1, 9, 9, 2]])

In [60]:
data_frame = pd.DataFrame(data)

In [61]:
data_frame

   0  1  2  3
0  9  5  5  4
1  7  7  4  1
2  4  9  2  3
3  1  9  9  2

In [62]:
type(data_frame)

pandas.core.frame.DataFrame

In [63]:
data_frame[0]

0    9
1    7
2    4
3    1
Name: 0, dtype: int64

In [64]:
type(data_frame[0])

pandas.core.series.Series

In [65]:
data_frame

   0  1  2  3
0  9  5  5  4
1  7  7  4  1
2  4  9  2  3
3  1  9  9  2

In [66]:
new_df = pd.DataFrame(data, index=["Gürhan","Ayşe","Elif","Melike"], columns = ["Ders1","Ders2", "Ders3","Ders4"])

In [67]:
new_df

        Ders1  Ders2  Ders3  Ders4
Gürhan      9      5      5      4
Ayşe        7      7      4      1
Elif        4      9      2      3
Melike      1      9      9      2

In [68]:
new_df['Ders1']

Gürhan    9
Ayşe      7
Elif      4
Melike    1
Name: Ders1, dtype: int64

In [69]:
new_df['Ders2']

Gürhan    5
Ayşe      7
Elif      9
Melike    9
Name: Ders2, dtype: int64

In [70]:
new_df['Ders3']

Gürhan    5
Ayşe      4
Elif      2
Melike    9
Name: Ders3, dtype: int64

In [71]:
# new_df['Gürhan']. - satır seçerken hata verir.

In [72]:
new_df.loc["Gürhan"]

Ders1    9
Ders2    5
Ders3    5
Ders4    4
Name: Gürhan, dtype: int64

In [73]:
new_df.loc["Elif"]

Ders1    4
Ders2    9
Ders3    2
Ders4    3
Name: Elif, dtype: int64

In [74]:
new_df.iloc[0]

Ders1    9
Ders2    5
Ders3    5
Ders4    4
Name: Gürhan, dtype: int64

In [75]:
new_df.iloc[1]

Ders1    7
Ders2    7
Ders3    4
Ders4    1
Name: Ayşe, dtype: int64

In [76]:
new_df.iloc[3]

Ders1    1
Ders2    9
Ders3    9
Ders4    2
Name: Melike, dtype: int64

In [77]:
new_df.loc[["Ayşe","Elif"]]

      Ders1  Ders2  Ders3  Ders4
Ayşe      7      7      4      1
Elif      4      9      2      3

In [78]:
new_df.loc["Gürhan":"Elif"]

        Ders1  Ders2  Ders3  Ders4
Gürhan      9      5      5      4
Ayşe        7      7      4      1
Elif        4      9      2      3

In [79]:
new_df.iloc[0:2]

        Ders1  Ders2  Ders3  Ders4
Gürhan      9      5      5      4
Ayşe        7      7      4      1

In [80]:
new_df.iloc[0:3]

        Ders1  Ders2  Ders3  Ders4
Gürhan      9      5      5      4
Ayşe        7      7      4      1
Elif        4      9      2      3

In [81]:
new_df.iloc[0:3,1:3]

        Ders2  Ders3
Gürhan      5      5
Ayşe        7      4
Elif        9      2

**Data Manipülasyon - Satır Sütun Ekleme Çıkarma **

In [82]:
new_df

        Ders1  Ders2  Ders3  Ders4
Gürhan      9      5      5      4
Ayşe        7      7      4      1
Elif        4      9      2      3
Melike      1      9      9      2

In [83]:
new_df["Ders5"] = 8

In [84]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5
Gürhan      9      5      5      4      8
Ayşe        7      7      4      1      8
Elif        4      9      2      3      8
Melike      1      9      9      2      8

In [85]:
new_df["Ders5"] = [3,4,5,6]

In [86]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5
Gürhan      9      5      5      4      3
Ayşe        7      7      4      1      4
Elif        4      9      2      3      5
Melike      1      9      9      2      6

In [87]:
new_df["Ders6"] = [2,4,5,1]

In [88]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      9      5      5      4      3      2
Ayşe        7      7      4      1      4      4
Elif        4      9      2      3      5      5
Melike      1      9      9      2      6      1

In [89]:
new_df["Ders7"] = new_df["Ders3"] * 3

In [90]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6  Ders7
Gürhan      9      5      5      4      3      2     15
Ayşe        7      7      4      1      4      4     12
Elif        4      9      2      3      5      5      6
Melike      1      9      9      2      6      1     27

In [91]:
new_df.drop("Ders7", axis=1) # Sütun silme axis parametresi 1 verildi. Sütun bazlı işlem için.

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      9      5      5      4      3      2
Ayşe        7      7      4      1      4      4
Elif        4      9      2      3      5      5
Melike      1      9      9      2      6      1

In [92]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6  Ders7
Gürhan      9      5      5      4      3      2     15
Ayşe        7      7      4      1      4      4     12
Elif        4      9      2      3      5      5      6
Melike      1      9      9      2      6      1     27

In [93]:
new_df_2 = new_df.drop("Ders7", axis=1) # Sütun silme işlemini kaydetmek için yeni değişkene atadık.

In [94]:
new_df_2

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      9      5      5      4      3      2
Ayşe        7      7      4      1      4      4
Elif        4      9      2      3      5      5
Melike      1      9      9      2      6      1

In [95]:
new_df.drop("Ders6", axis=1 , inplace=True) #inplace parametresi TRUE değeri atandığında dataframe içinde o işlemi yapıyor ve kaydediyor. Yoksa yukarıda yapıldığı gibi bir değişkene atanmalı.

In [96]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      9      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27

In [97]:
new_df.drop("Melike", axis=0)

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      9      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6

In [98]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      9      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27

In [99]:
new_df.loc["Mehmet"] = 15

In [100]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      9      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27
Mehmet     15     15     15     15     15     15

In [101]:
new_df.loc["Ahmet"] = [3,5,7,8,9,3]

In [102]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      9      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27
Mehmet     15     15     15     15     15     15
Ahmet       3      5      7      8      9      3

In [103]:
new_df.iloc[0,0:1] = 8

In [104]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27
Mehmet     15     15     15     15     15     15
Ahmet       3      5      7      8      9      3

In [105]:
new_df.loc["Ahmet","Ders1"] = 5

In [106]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27
Mehmet     15     15     15     15     15     15
Ahmet       5      5      7      8      9      3

In [107]:
new_df.loc["Mehmet","Ders1"] = 6

In [108]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Elif        4      9      2      3      5      6
Melike      1      9      9      2      6     27
Mehmet      6     15     15     15     15     15
Ahmet       5      5      7      8      9      3

**Filtrelemeler**

In [109]:
bool_frame = new_df > 5

In [110]:
bool_frame

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan   True  False  False  False  False   True
Ayşe     True   True  False  False  False   True
Elif    False   True  False  False  False   True
Melike  False   True   True  False   True   True
Mehmet   True   True   True   True   True   True
Ahmet   False  False   True   True   True  False

In [111]:
new_df[new_df > 5]

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan    8.0    NaN    NaN    NaN    NaN   15.0
Ayşe      7.0    7.0    NaN    NaN    NaN   12.0
Elif      NaN    9.0    NaN    NaN    NaN    6.0
Melike    NaN    9.0    9.0    NaN    6.0   27.0
Mehmet    6.0   15.0   15.0   15.0   15.0   15.0
Ahmet     NaN    NaN    7.0    8.0    9.0    NaN

In [112]:
new_df[new_df["Ders1"]>5]

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      5      5      4      3     15
Ayşe        7      7      4      1      4     12
Mehmet      6     15     15     15     15     15

**.csv dosya okuma, gerçek dataları içeri alma. **

In [116]:
notlar_df = pd.read_csv("/content/ECS_Veri_Bilimi_Yapay_Zeka_notlar_eksik_new.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/ECS_Veri_Bilimi_Yapay_Zeka_notlar_eksik_new.csv'

In [115]:
notlar_df

NameError: name 'notlar_df' is not defined

In [ ]:
notlar_df.head() # data frame'in ilk 5 verisini getirir.

In [ ]:
notlar_df.tail() # data frame'in son 5 verisini getirir.

In [ ]:
notlar_df.describe() # dataframe hakkında temel istatistiksel verileri veriyor.

In [ ]:
notlar_df.shape # satır ve sütun sayıları

In [ ]:
notlar_df.columns

In [ ]:
notlar_df.info()# Dataframe Sütunları ile ilgili genel bilgi.

In [ ]:
notlar_df.isna() # boş değerler ile ilgili boşta true

In [ ]:
notlar_df["sinav1"].isna() # boş değerler ile ilgili sütun seçtik. boşsa true

In [ ]:
notlar_df

In [ ]:
notlar_df.drop("proje", axis=1)

In [ ]:
notlar_df

In [ ]:
notlar_df.fillna(10) #tüm boşlukları "10 sayısı ile doldur." neden 10 çünkü o değeri atadık bir önemi yok. 20 30 50 olabilir.

In [ ]:
notlar_df

In [ ]:
notlar_df.mean() # Genel Sütun ortalamaları

In [ ]:
notlar_df.fillna(notlar_df.mean()) #Tüm boşlukları sütun ortalamaları ile doldur.

In [ ]:
notlar_df.max() #sütun maximum değerleri

In [ ]:
notlar_df.min() #sütun minumum değerleri

In [ ]:
notlar_df

In [ ]:
notlar_df["sinav1"] = notlar_df["sinav1"].fillna(notlar_df["sinav1"].mean() ) # tek bir sütunun eksik verilerini doldurma.

In [ ]:
notlar_df

**CONCAT Kavramı - MERGE Kavramı**

In [ ]:
df = pd.read_csv("/content/5. Ders - concat_data1.csv")

In [ ]:
df

In [ ]:
df2 = pd.read_csv("/content/5. Ders - concat_data2.csv")

In [ ]:
df2

In [ ]:
df_concat = pd.concat([df,df2], ignore_index=True)

In [ ]:
df_concat

In [ ]:
df3 = pd.read_csv("/content/5. Ders - merge_data1.csv")

In [114]:
df3

NameError: name 'df3' is not defined

In [ ]:
df4 = pd.read_csv("/content/5. Ders - merge_data2.csv")

In [ ]:
df4

In [ ]:
df_merge = pd.merge(df3, df4, on="Employee_ID", how="inner")

In [ ]:
df_merge

In [ ]:
df_merge2 = pd.merge(df3, df4, on="Employee_ID", how="outer")

In [ ]:
df_merge2

In [ ]:
df_merge3 = pd.merge(df3, df4, on="Employee_ID", how="left")

In [ ]:
df_merge3

In [ ]:
df_merge4 = pd.merge(df3, df4, on="Employee_ID", how="right")

In [ ]:
df_merge4